name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'old issue sanse activity issue message'
        stale-pr-message: 'old issue sanse activity pull request message'
        stale-issue-label: 'old issue sanse activity'
        stale-pr-label: 'old issue sanse activity'
